project:
  type: website

website:
  title: "VD_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Visualización de Datos.qmd
        text: Visualización de Datos

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

